plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.comicarchive'
version = '0.1.0'

android {
  namespace "expo.modules.comicarchive"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  // libarchive per Android: legge ZIP/CBZ, RAR/CBR (anche RAR5), 7Z/CB7, TAR/CBT.
  // È la stessa libreria usata da Mihon (lettore manga open source).
  implementation 'me.zhanghai.android.libarchive:library:1.1.7'
}
